services:
  db:
    # コンテナの名前を指定
    container_name: db
    # コンテナの再起動を指定
    restart: always
    # データベースのイメージを指定
    # ./db/Dockerfile を使用してビルド
    build:
      context: ./db
    # データベースの環境変数を指定
    environment:
      MARIADB_ROOT_PASSWORD: tmcit
      MARIADB_DATABASE: LESSON
      MARIADB_USER: tmcit
      MARIADB_PASSWORD: tmcit
      TZ: 'Asia/Tokyo'
    # データベースのボリュームを指定
    volumes:
      # データベースのデータを保存するボリューム
      - ./db/data:/var/lib/mysql
      # データベースのログを保存するボリューム
      - ./logs/mariadb:/var/log/mysql
      # データベースの設定ファイルを保存するボリューム
      - ./config/mariadb/my.cnf:/etc/mysql/my.cnf
    # データベースの起動時に実行するコマンド
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  app:
    # コンテナの名前を指定
    container_name: app
    # ./src/Dockerfile を使用してビルド
    build:
      context: ./src
    ports:
      - 8080:80
    # コンテナの依存関係を指定
    # dbコンテナが起動してからappコンテナを起動
    depends_on:
      - db
    volumes:
      - ./src:/var/www/laravel
      - ./src/storage/logs:/var/www/laravel/storage/logs
      - ./src/.env:/var/www/laravel/.env
      - ./logs/apache:/var/log/apache2
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf